version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pardakht_yar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/pardakht_yar
      PORT: 5000
      NODE_ENV: development
      JWT_SECRET: your_jwt_secret_key
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3030:3030"
    depends_on:
      - server
    environment:
      VITE_API_URL: http://localhost:5050/api
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
